usuarios/applications/home/urls.py
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path("panel/", views.HomePage.as_view(), name='panel'),
    path("mixin/", views.TemplatePruebaMixin.as_view(), name=',mixin'),
]

usuarios/applications/users/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name='add-user'),
    path("login/", views.LoginUser.as_view(), name='login-user'),
    path("logout/", views.LogoutUser.as_view(), name='logout-user'),
    path("update/", views.UpdatePassword.as_view(), name='update-user'),
    path("verify/<pk>/", views.CodeVerificationView.as_view(), name='verify-user'),
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls', namespace='users')),
    path('', include('applications.home.urls', namespace='home')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/home/views.py
import datetime

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.urls import reverse_lazy, reverse

class FechaMixin(object):
    
    def get_context_data(self, **kwargs):
        context = super(FechaMixin,self).get_context_data(**kwargs)
        context["fecha"] = datetime.datetime.now() 
        return context
    


class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:login-user')
    
    
class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = 'home/mixin.html'

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Panel de usuario</h1>
    <h3>Bienvenido: {{user}} </h3>

    {{fecha}}

    <ul>
        <li><a href="{% url 'users_app:logout-user'%}">Cerrar Sesion</a></li>
        <li><a href="{% url 'users_app:update-user'%}">Actualizar Password</a></li>
    </ul>

</body>
</html>

usuarios/templates/home/mixin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Mixin</h1>

    {{fecha}}

</body>
</html>